#!/usr/bin/env python3
import matplotlib.pyplot as plt
from math import pi, sin, cos

x = []
y = []
t = -6
t_total = 6

###Fourier terms
m = 100
period = 4
omega = 2*pi/period
c_k = [(1/(2*omega*k))*(sin(omega*k)+cos(omega*k)/(omega*k)-1/(omega*k)) for k in range(1,m)]
d_k = [(1/(2*omega*k))*(sin(omega*k)/(omega*k)-cos(omega*k)) for k in range(1,m)]
c_k.insert(0, 1/8)
d_k.insert(0, 0)


while t<t_total:
    x.append(t)
    sum_ = 0
    for k in range(m):
        sum_ += c_k[k]*cos(omega*k*t) + d_k[k]*sin(omega*k*t)
    y.append(sum_)
    t+= 0.01
    
plt.plot(x, y)
plt.show()
